import java.net.URI

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// ---------------------------------------------------------------------------
// MediaTek asset vendoring
//
// The upstream engine ships ~48 MB of Download Agent binaries and ~325 KB of
// exploit payloads. Those are deliberately NOT committed to git: they are
// fetched once at build time and packaged into the APK, so the installed app is
// completely self-contained and works offline.
//
//   -PmtkclientDir=<path>   vendor from a local checkout (no network needed)
//   -PmtkclientRef=<ref>    upstream git ref to fetch (default: main)
//   -PslimAssets=true       omit Loader/ DA binaries -> BROM-only, ~2 MB APK
// ---------------------------------------------------------------------------
val mtkclientDirProp = providers.gradleProperty("mtkclientDir")
val mtkclientRef = providers.gradleProperty("mtkclientRef").getOrElse("main")
val slimAssets = providers.gradleProperty("slimAssets").getOrElse("false").toBoolean()

val mtkSrcDir = layout.buildDirectory.dir("mtkclient-src")
val mtkAssetsDir = layout.buildDirectory.dir("generated/mtkAssets")

val fetchMtkclient by tasks.registering {
    group = "mtk"
    description = "Obtain the upstream mtkclient tree (local checkout or GitHub tarball)."
    val dest = mtkSrcDir
    val localDir = mtkclientDirProp
    val ref = mtkclientRef
    outputs.dir(dest)
    doLast {
        val outRoot = dest.get().asFile
        val marker = File(outRoot, "mtkclient/payloads")
        if (marker.isDirectory) {
            logger.lifecycle("mtk: reusing cached source tree at {}", outRoot)
            return@doLast
        }

        val local = localDir.orNull
        if (!local.isNullOrBlank()) {
            val src = File(local)
            require(src.isDirectory) { "mtkclientDir does not exist: $local" }
            // Accept either a repo root or the inner mtkclient/ package dir.
            val pkg = if (File(src, "payloads").isDirectory) src.parentFile else src
            require(File(pkg, "mtkclient/payloads").isDirectory) {
                "Could not locate mtkclient/payloads under $local"
            }
            logger.lifecycle("mtk: vendoring from local checkout {}", pkg)
            copy {
                from(File(pkg, "mtkclient"))
                into(File(outRoot, "mtkclient"))
            }
            return@doLast
        }

        val tgz = layout.buildDirectory.file("mtkclient-$ref.tar.gz").get().asFile
        if (!tgz.isFile) {
            val url = "https://codeload.github.com/bkerler/mtkclient/tar.gz/refs/heads/$ref"
            logger.lifecycle("mtk: downloading {}", url)
            tgz.parentFile.mkdirs()
            URI(url).toURL().openStream().use { input ->
                tgz.outputStream().use { output -> input.copyTo(output) }
            }
        }

        val staging = File(outRoot, "_extract")
        delete(staging)
        copy {
            from(tarTree(resources.gzip(tgz)))
            into(staging)
        }
        // The tarball unpacks to a single top-level directory named after the ref.
        val unpacked = staging.listFiles()?.firstOrNull { it.isDirectory }
            ?: error("mtk: tarball contained no directory")
        copy {
            from(File(unpacked, "mtkclient"))
            into(File(outRoot, "mtkclient"))
        }
        delete(staging)
        require(marker.isDirectory) { "mtk: extraction did not produce mtkclient/payloads" }
    }
}

val syncMtkAssets by tasks.registering(Sync::class) {
    group = "mtk"
    description = "Stage the vendored payloads/loaders into the APK asset directory."
    dependsOn(fetchMtkclient)
    from(mtkSrcDir.map { it.dir("mtkclient/payloads") }) {
        into("payloads")
    }
    if (!slimAssets) {
        from(mtkSrcDir.map { it.dir("mtkclient/Loader") }) {
            into("loader")
            // 838 device-specific preloader dumps are only needed by the DA /
            // preloader-repair paths; BROM core does not read them.
            exclude("Preloader/**")
        }
    }
    into(mtkAssetsDir)
    doLast {
        val root = mtkAssetsDir.get().asFile
        val bytes = root.walkTopDown().filter { it.isFile }.sumOf { it.length() }
        logger.lifecycle("mtk: staged {} MiB of assets (slim={})", "%.2f".format(bytes / 1048576.0), slimAssets)
    }
}

android {
    namespace = "dev.cocyce.mtknative"
    compileSdk = 34

    defaultConfig {
        applicationId = "dev.cocyce.mtknative"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    // Assets are generated by syncMtkAssets; expose them as an extra srcDir.
    sourceSets {
        getByName("main") {
            assets.srcDir(mtkAssetsDir)
        }
    }

    signingConfigs {
        // Populated by CI from secrets when available; local builds fall back to
        // the debug key so `assembleRelease` always produces an installable APK.
        create("ci") {
            val storePath = providers.environmentVariable("MTK_KEYSTORE_FILE").orNull
            if (!storePath.isNullOrBlank() && File(storePath).isFile) {
                storeFile = File(storePath)
                storePassword = providers.environmentVariable("MTK_KEYSTORE_PASSWORD").orNull
                keyAlias = providers.environmentVariable("MTK_KEY_ALIAS").orNull
                keyPassword = providers.environmentVariable("MTK_KEY_PASSWORD").orNull
            }
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            val ciSigning = signingConfigs.getByName("ci")
            signingConfig = if (ciSigning.storeFile != null) ciSigning else signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += setOf("/META-INF/{AL2.0,LGPL2.1}")
        }
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }

    lint {
        abortOnError = false
        warningsAsErrors = false
    }
}

// Guarantee the generated asset tree exists before AGP merges assets.
tasks.named("preBuild") {
    dependsOn(syncMtkAssets)
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.google.material)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
    // Parses golden_vectors.json on the JVM, where android.jar only stubs org.json.
    testImplementation(libs.json)
    testImplementation(libs.kotlinx.coroutines.test)
}
